/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ces;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.text.DecimalFormat;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author Page One
 */
public class Gcash extends javax.swing.JFrame {

    /**
     * Creates new form Gcash
     */
    public Gcash() {
        initComponents();
        
        
    }
    
    public void setText(String sb, String selectedComboBoxItem, String amount, String studentID){
        
        
        referenceCode.setText(sb.toString());
        sID.setText(studentID);
        selectedItem.setText(selectedComboBoxItem);
        
        DecimalFormat dc = new DecimalFormat("###,###.00");
        
        double format = Double.parseDouble(amount);
        String format1 = dc.format(format);
        
        Fee.setText(format1);
        Total.setText(format1);
        mstrAmount.setText(format1 + " PHP");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Card = new javax.swing.JPanel();
        checkOut = new javax.swing.JPanel();
        jPanel4 = new RoundedPanel(55, new Color(55,111,138));
        Total = new javax.swing.JLabel();
        Fee = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        referenceCode = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        selectedItem = new javax.swing.JLabel();
        sID = new javax.swing.JLabel();
        jPanel2 = new RoundedPanel(55, new Color(55,111,138));
        jLabel10 = new javax.swing.JLabel();
        masterCard = new javax.swing.JButton();
        gcashBttn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Gcash = new javax.swing.JPanel();
        jPanel5 = new RoundedPanel(55, new Color(55,111,138));
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        n = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        backBttn = new javax.swing.JLabel();
        mstrCard = new javax.swing.JPanel();
        jPanel6 = new RoundedPanel(55, new Color(55,111,138));
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        mstrAmount = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        payButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        backBtn = new javax.swing.JLabel();
        mstrReceipt = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setBackground(new java.awt.Color(36, 48, 51));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Card.setBackground(new java.awt.Color(36, 46, 51));
        Card.setLayout(new java.awt.CardLayout());

        checkOut.setBackground(new java.awt.Color(36, 48, 51));
        checkOut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(36, 48, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Total.setFont(new java.awt.Font("SansSerif", 1, 19)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 255, 255));
        Total.setText("5,600.00");
        jPanel4.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 80, 20));

        Fee.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Fee.setText("5,600.00");
        jPanel4.add(Fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 70, 30));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TOTAL:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 430, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel15.setText("Reference");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel16.setText("Item:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 25)); // NOI18N
        jLabel17.setText("Student ID:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ces/blueL.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 160, 640, 20));

        referenceCode.setFont(new java.awt.Font("SansSerif", 1, 56)); // NOI18N
        referenceCode.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(referenceCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 320, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ces/blueL.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 570, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ces/blueL.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 590, 20));

        selectedItem.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        selectedItem.setText("Tuition Fee");
        jPanel4.add(selectedItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        sID.setFont(new java.awt.Font("SansSerif", 1, 29)); // NOI18N
        jPanel4.add(sID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 130, 50));

        checkOut.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 620, 390));

        jPanel2.setBackground(new java.awt.Color(36, 48, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("SansSerif", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Pay with");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 160, -1));

        masterCard.setBackground(new java.awt.Color(55, 111, 138));
        masterCard.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        masterCard.setForeground(new java.awt.Color(255, 255, 255));
        masterCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ces/Mastercard-Logo.wine.png"))); // NOI18N
        masterCard.setText("MasterCard");
        masterCard.setBorder(null);
        masterCard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        masterCard.setIconTextGap(10);
        masterCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterCardActionPerformed(evt);
            }
        });
        jPanel2.add(masterCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 180, 70));

        gcashBttn.setBackground(new java.awt.Color(55, 111, 138));
        gcashBttn.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        gcashBttn.setForeground(new java.awt.Color(255, 255, 255));
        gcashBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ces/gcas.png"))); // NOI18N
        gcashBttn.setText("Gcash");
        gcashBttn.setBorder(null);
        gcashBttn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gcashBttn.setIconTextGap(10);
        gcashBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gcashBttnActionPerformed(evt);
            }
        });
        jPanel2.add(gcashBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 140, 70));

        checkOut.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 720, 620, 180));

        jLabel8.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Checkout");
        checkOut.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 180, 160, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 56)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Online Payment");
        checkOut.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 400, -1));

        Card.add(checkOut, "card2");

        Gcash.setBackground(new java.awt.Color(36, 48, 51));
        Gcash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(36, 48, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 19)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("5,600.00");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 80, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("5,600.00");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 70, 30));

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("TOTAL:");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 430, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel21.setText("Reference");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel22.setText("Item:");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 25)); // NOI18N
        jLabel23.setText("Student ID:");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ces/blueL.png"))); // NOI18N
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 160, 640, 20));

        n.setFont(new java.awt.Font("SansSerif", 1, 56)); // NOI18N
        n.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 320, 60));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ces/blueL.png"))); // NOI18N
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 570, 20));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ces/blueL.png"))); // NOI18N
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 590, 20));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel26.setText("Tuition Fee");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel27.setFont(new java.awt.Font("SansSerif", 1, 27)); // NOI18N
        jLabel27.setText("536523");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 110, -1));

        Gcash.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 620, 390));

        backBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ces/backBtn.png"))); // NOI18N
        backBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBttnMouseClicked(evt);
            }
        });
        Gcash.add(backBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 100));

        Card.add(Gcash, "card3");

        mstrCard.setBackground(new java.awt.Color(36, 48, 51));
        mstrCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(36, 48, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ces/blueL.png"))); // NOI18N
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 120, 630, 20));

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 56)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Online Payment");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 400, -1));

        mstrAmount.setFont(new java.awt.Font("SansSerif", 0, 40)); // NOI18N
        mstrAmount.setForeground(new java.awt.Color(255, 255, 255));
        mstrAmount.setText("AMOUNT");
        jPanel6.add(mstrAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 270, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MetaLabs IPG:");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabel6.setText("Expiry Year*");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        jTextField1.setBackground(new java.awt.Color(98, 161, 192));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 380, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\63981\\OneDrive\\Desktop\\HumaNexus\\mcard.png")); // NOI18N
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 40, 30));

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\63981\\OneDrive\\Desktop\\HumaNexus\\visa.png")); // NOI18N
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 50, 30));

        jLabel30.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabel30.setText("Expiry Month*");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(98, 161, 192));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YY", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44" }));
        jPanel6.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 80, 30));

        jComboBox2.setBackground(new java.awt.Color(98, 161, 192));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MM", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "" }));
        jComboBox2.setToolTipText("");
        jPanel6.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 80, 30));

        jLabel31.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabel31.setText("Card Number*");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel32.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabel32.setText("Cardholder Name*");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jTextField2.setBackground(new java.awt.Color(98, 161, 192));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 490, 50));

        jLabel33.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabel33.setText("Security Code*");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        jTextField3.setBackground(new java.awt.Color(98, 161, 192));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 120, 50));

        jLabel2.setFont(new java.awt.Font("SansSerif", 2, 15)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ces/securityCode.png"))); // NOI18N
        jLabel2.setText("3  digits on back of your card");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, -1, -1));

        payButton.setBackground(new java.awt.Color(98, 161, 192));
        payButton.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        payButton.setText("Pay");
        payButton.setBorder(null);
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });
        jPanel6.add(payButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 620, 110, 60));

        jButton2.setBackground(new java.awt.Color(55, 111, 138));
        jButton2.setFont(new java.awt.Font("SansSerif", 2, 26)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 630, -1, -1));

        mstrCard.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 590, 770));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ces/backBtn.png"))); // NOI18N
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });
        mstrCard.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 100));

        Card.add(mstrCard, "card4");

        mstrReceipt.setBackground(new java.awt.Color(36, 48, 51));
        mstrReceipt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        mstrReceipt.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, -1, -1));

        Card.add(mstrReceipt, "card5");

        Panel.add(Card, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void masterCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterCardActionPerformed
        // TODO add your handling code here:
        Card.removeAll();
        Card.add(mstrCard);
        Card.repaint();
        Card.revalidate();  
        
    }//GEN-LAST:event_masterCardActionPerformed

    private void gcashBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gcashBttnActionPerformed
        // TODO add your handling code here:
        Card.removeAll();
        Card.add(Gcash);
        Card.repaint();
        Card.revalidate();
    }//GEN-LAST:event_gcashBttnActionPerformed

    private void backBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBttnMouseClicked
        // TODO add your handling code here:
        Card.removeAll();
        Card.add(checkOut);
        Card.repaint();
        Card.revalidate();
    }//GEN-LAST:event_backBttnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        // TODO add your handling code here:
          Card.removeAll();
        Card.add(checkOut);
        Card.repaint();
        Card.revalidate();
    }//GEN-LAST:event_backBtnMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gcash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Card;
    private javax.swing.JLabel Fee;
    private javax.swing.JPanel Gcash;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel backBtn;
    private javax.swing.JLabel backBttn;
    private javax.swing.JPanel checkOut;
    private javax.swing.JButton gcashBttn;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton masterCard;
    private javax.swing.JLabel mstrAmount;
    private javax.swing.JPanel mstrCard;
    private javax.swing.JPanel mstrReceipt;
    private javax.swing.JLabel n;
    private javax.swing.JButton payButton;
    private javax.swing.JLabel referenceCode;
    private javax.swing.JLabel sID;
    private javax.swing.JLabel selectedItem;
    // End of variables declaration//GEN-END:variables

class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }


}
